version: "3.8"
services:
  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Link the source code.
  backend:
    depends_on:
      - db
    build: ./backend
    ports:
      - "3900:3900"
    command: ./docker-entrypoint.sh
    environment:
      DB_URL: mongodb://db/movies # Environment variable
    volumes:
      - ./backend:/app # Link the source code.
  db:
    image: mongo:4.0-xenial # Pull mongodb image. Build on top of Xenial (Ubuntu Version 16).
    ports:
      - "27017:27017"
    volumes:
      - movies:/data/db
volumes:
  movies: # Create an empty volume
