---
version: "3.8"
volumes:
  movies:  # Create an empty volume
services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    build: ./backend
    ports:
      - "3001:3001"
    command: ./docker-entrypoint.sh
    environment:
      DB_URL: mongodb://db/movies # Environment variable
  database:
    image: mongo:4.0-xenial # Pull mongo image build on top of Ubuntu Xenial
    ports:
      - "27017:27017"
    volumes:
      - movies:/data/db
